build:
	docker-compose build --no-cache
up:
	docker-compose up -d
stop:
	docker-compose stop
test:
	 docker-compose exec php bin/phpunit
down:
	docker-compose down
install:
	docker-compose exec php composer install
